NAME_FORMAT = /\A[A-Za-z\d\-\_]*\z/
EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
ENDPOINT_TOKEN_REGEN_RANDOM = 10
MAX_FILE_SIZE = 5.gigabytes
MIN_NAME_LENGTH = 3
MAX_NAME_LENGTH = 39
MAX_EMAIL_LENGTH = 105
MAX_PACKAGE_NAME_LENGTH = 100
